In [ ]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
data=pd.read_csv('train.csv')
data.fillna(0)

Dates        Category  ...           X          Y
0       2015-05-13 23:53:00        WARRANTS  ... -122.425892  37.774599
1       2015-05-13 23:53:00  OTHER OFFENSES  ... -122.425892  37.774599
2       2015-05-13 23:33:00  OTHER OFFENSES  ... -122.424363  37.800414
3       2015-05-13 23:30:00   LARCENY/THEFT  ... -122.426995  37.800873
4       2015-05-13 23:30:00   LARCENY/THEFT  ... -122.438738  37.771541
...                     ...             ...  ...         ...        ...
267253  2011-09-25 13:20:00   LARCENY/THEFT  ... -122.391886  37.709790
267254  2011-09-25 13:00:00   VEHICLE THEFT  ... -122.406300  37.775513
267255  2011-09-25 13:00:00        GAMBLING  ... -122.403405  37.775421
267256  2011-09-25 13:00:00       VANDALISM  ... -122.417609  37.800120
267257  2011-09-25 13:00:00   VEHICLE THEFT  ... -122.388278   0.000000

[267258 rows x 9 columns]

In [ ]:
x=data.iloc[:,[1,2,3,4]].values
y=data.iloc[:,5].values

In [ ]:
print(x)
print(y)

[['WARRANTS' 'WARRANT ARREST' 'Wednesday' 'NORTHERN']
 ['OTHER OFFENSES' 'TRAFFIC VIOLATION ARREST' 'Wednesday' 'NORTHERN']
 ['OTHER OFFENSES' 'TRAFFIC VIOLATION ARREST' 'Wednesday' 'NORTHERN']
 ...
 ['GAMBLING' 'GAMBLING' 'Sunday' 'SOUTHERN']
 ['VANDALISM' 'MALICIOUS MISCHIEF, VANDALISM' 'Sunday' 'CENTRAL']
 ['VEHICLE THEFT' 'ATTEMPTED STOLEN VEHICLE' 'Sunday' 'BAYVIEW']]
['ARREST, BOOKED' 'ARREST, BOOKED' 'ARREST, BOOKED' ... 'NONE' 'NONE'
 'NONE']


In [ ]:
x[:,0]=LabelEncoder().fit_transform(x[:,0])

In [ ]:
x[:,1]=LabelEncoder().fit_transform(x[:,1])

In [ ]:
x[:,2]=LabelEncoder().fit_transform(x[:,2])

In [ ]:
x[:,3]=LabelEncoder().fit_transform(x[:,3])

In [ ]:
print(x)

[[37 790 6 4]
 [21 738 6 4]
 [21 738 6 4]
 ...
 [14 356 3 7]
 [35 449 3 1]
 [36 100 3 0]]


In [ ]:
y=LabelEncoder().fit_transform(y)

In [ ]:
print(y)

[ 0  0  0 ... 11 11 11]


In [ ]:
# splitting training and test data
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85,random_state=0)
# for checking the values
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[20 430 1 9]
 [36 670 0 4]
 [16 364 1 4]
 ...
 [1 122 2 4]
 [20 430 3 9]
 [16 364 5 9]]
[[16 368 2 7]
 [16 500 3 8]
 [13 212 3 4]
 ...
 [21 738 2 9]
 [21 562 0 4]
 [20 351 3 3]]
[11 11 11 ...  0 11 11]
[11 11 11 ...  0  0 11]


In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x)
print(y)

[[37 790 6 4]
 [21 738 6 4]
 [21 738 6 4]
 ...
 [14 356 3 7]
 [35 449 3 1]
 [36 100 3 0]]
[ 0  0  0 ... 11 11 11]


In [ ]:
clf = DecisionTreeClassifier(criterion='gini',max_depth=5)

In [ ]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
print(y_pred)
print(y_test)

[11 11 11 ...  0  0 11]
[11 11 11 ...  0  0 11]


In [ ]:
a=int(input("Write Category value"))
b=int(input("Write Descript value"))
c=int(input("Write DayOfWeek value"))
d=int(input("Write PdDistrict Value"))

Write Category value396
Write Descript value0
Write DayOfWeek value456
Write PdDistrict Value34


In [ ]:
t1=sc.transform([[a,b,c,d]])
pt1=clf.predict(t1)
pt1

array([0])