Decision Tree Algorithm (Classification)

In [ ]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv('job.csv')
print(data.head())
print(data.columns)

   ID  JobFamily    JobFamilyDescription  ...  ContactLevel FinancialBudget    PG
0   1          1  Accounting And Finance  ...             3               5  PG05
1   2          1  Accounting And Finance  ...             7               7  PG06
2   3          1  Accounting And Finance  ...             7              10  PG08
3   4          1  Accounting And Finance  ...             8              11  PG10
4   5          2  Administrative Support  ...             1               1  PG01

[5 rows x 14 columns]
Index(['ID', 'JobFamily', 'JobFamilyDescription', 'JobClass',
       'JobClassDescription', 'PayGrade', 'EducationLevel', 'Experience',
       'OrgImpact', 'ProblemSolving', 'Supervision', 'ContactLevel',
       'FinancialBudget', 'PG'],
      dtype='object')


In [ ]:
x=data.iloc[:,[5,6,7,8,9,10,11]].values
y=data.iloc[:,12].values
print(x)
print(y)

[[ 5  3  1  3  3  4  3]
 [ 6  4  1  5  4  5  7]
 [ 8  4  2  6  5  6  7]
 [10  5  5  6  6  7  8]
 [ 1  1  0  1  1  1  1]
 [ 2  1  1  1  1  1  2]
 [ 3  1  2  1  2  1  3]
 [ 4  4  0  1  2  1  3]
 [ 5  4  0  4  3  5  7]
 [ 4  2  0  1  4  1  1]
 [ 6  2  0  3  4  1  6]
 [ 9  2  0  4  5  5  6]
 [ 5  1  0  3  4  3  7]
 [ 6  3  0  3  4  5  6]
 [ 9  4  0  4  5  7  6]
 [10  5  0  6  6  7  8]
 [ 2  1  0  1  2  1  1]
 [ 3  1  1  1  2  1  1]
 [ 4  1  1  3  3  4  3]
 [ 5  3  2  3  4  5  8]
 [ 5  2  1  3  3  4  3]
 [ 8  4  0  6  5  6  7]
 [ 9  4 10  6  5  6  7]
 [ 1  1  2  2  1  2  1]
 [ 3  3  3  2  3  4  2]
 [ 6  4  2  4  4  5  7]
 [ 4  2  0  1  3  4  4]
 [ 5  4  0  1  2  1  3]
 [ 8  5  2  5  5  6  7]
 [ 2  1  0  1  1  1  1]
 [ 3  1  1  1  2  1  3]
 [ 5  4  0  1  3  1  4]
 [ 7  4  0  3  4  5  7]
 [ 2  1  0  1  2  1  1]
 [ 4  1  0  3  3  4  5]
 [ 5  2  0  3  4  4  5]
 [10  6  5  6  6  7  7]
 [ 2  1  0  1  1  1  1]
 [ 4  3  0  3  2  1  1]
 [ 5  4  2  3  4  4  1]
 [ 8  6  5  4  5  6  7]
 [ 5  4  1  3  4

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.5,random_state=3)
# for checking the values
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 2  1  0  1  1  1  1]
 [ 4  4  0  1  2  1  3]
 [10  5  5  6  6  7  8]
 [ 9  5  5  6  5  6  7]
 [ 2  1  0  1  2  1  1]
 [ 2  1  1  1  1  1  2]
 [10  5  5  6  6  7  8]
 [ 6  4  1  5  4  5  7]
 [ 6  4  2  3  4  5  6]
 [ 8  4  2  6  5  6  7]
 [ 9  4 10  6  5  6  7]
 [ 8  5  5  6  5  4  7]
 [ 3  1  1  1  2  1  1]
 [ 4  2  0  1  3  4  4]
 [ 9  4  0  4  5  7  6]
 [ 5  4  2  3  4  4  1]
 [ 2  1  0  1  1  1  1]
 [ 5  4  2  3  3  4  3]
 [ 5  2  1  3  3  4  3]
 [ 7  4  0  3  4  5  7]
 [ 4  3  0  3  2  1  1]
 [ 8  4  0  4  5  6  7]
 [ 4  3  0  1  2  1  3]
 [ 5  4  1  3  4  4  3]
 [ 9  4  3  6  5  6  7]
 [ 6  2  0  3  4  1  6]
 [ 5  3  2  3  4  5  8]
 [ 8  4  0  6  5  6  7]
 [ 5  3  1  3  3  4  3]
 [ 5  4  0  4  3  5  7]
 [ 3  1  2  3  2  1  2]
 [10  5  5  6  6  7  8]
 [ 3  3  3  2  3  4  2]]
[[ 5  4  1  3  3  4  3]
 [ 9  2  0  4  5  5  6]
 [ 5  4  0  1  2  1  3]
 [ 3  1  2  1  2  1  3]
 [ 6  4  2  4  4  5  7]
 [ 1  1  0  1  1  1  1]
 [ 8  5  5  6  5  6  7]
 [ 6  5  2  4  4  5  7]
 [ 8  5  2  5  

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x)
print(y)

[[ 5  3  1  3  3  4  3]
 [ 6  4  1  5  4  5  7]
 [ 8  4  2  6  5  6  7]
 [10  5  5  6  6  7  8]
 [ 1  1  0  1  1  1  1]
 [ 2  1  1  1  1  1  2]
 [ 3  1  2  1  2  1  3]
 [ 4  4  0  1  2  1  3]
 [ 5  4  0  4  3  5  7]
 [ 4  2  0  1  4  1  1]
 [ 6  2  0  3  4  1  6]
 [ 9  2  0  4  5  5  6]
 [ 5  1  0  3  4  3  7]
 [ 6  3  0  3  4  5  6]
 [ 9  4  0  4  5  7  6]
 [10  5  0  6  6  7  8]
 [ 2  1  0  1  2  1  1]
 [ 3  1  1  1  2  1  1]
 [ 4  1  1  3  3  4  3]
 [ 5  3  2  3  4  5  8]
 [ 5  2  1  3  3  4  3]
 [ 8  4  0  6  5  6  7]
 [ 9  4 10  6  5  6  7]
 [ 1  1  2  2  1  2  1]
 [ 3  3  3  2  3  4  2]
 [ 6  4  2  4  4  5  7]
 [ 4  2  0  1  3  4  4]
 [ 5  4  0  1  2  1  3]
 [ 8  5  2  5  5  6  7]
 [ 2  1  0  1  1  1  1]
 [ 3  1  1  1  2  1  3]
 [ 5  4  0  1  3  1  4]
 [ 7  4  0  3  4  5  7]
 [ 2  1  0  1  2  1  1]
 [ 4  1  0  3  3  4  5]
 [ 5  2  0  3  4  4  5]
 [10  6  5  6  6  7  7]
 [ 2  1  0  1  1  1  1]
 [ 4  3  0  3  2  1  1]
 [ 5  4  2  3  4  4  1]
 [ 8  6  5  4  5  6  7]
 [ 5  4  1  3  4

In [ ]:
clf = DecisionTreeClassifier(criterion='gini',max_depth=5)

In [ ]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
print(y_pred)
print(y_test)

[ 5  7  5  1  7  1 10  7 10 11  5  4  7 10  7  4  4  1  1  1  1  5  1  1
  3 11  5 10  7  1  7  1 11]
[ 4 10  4  3  7  1  7  5 10 11  3  4  2 11  7  7  5  4  3  2  2  4  1  5
  1 11  3 10  1  2  7  1 11]


In [ ]:
a=int(input("Write paygrade value"))
b=int(input("Write Educationlevel value"))
c=int(input("Write Experience value"))
d=int(input("Write OrgImpact Value"))
e=int(input("Write ProblemSolving value"))
f=int(input("Write Supervision value"))
g=int(input("Write ContactLevel value"))

Write paygrade value2
Write Educationlevel value5
Write Experience value10
Write OrgImpact Value5
Write ProblemSolving value9
Write Supervision value3
Write ContactLevel value8


In [ ]:
t1=sc.transform([[a,b,c,d,e,f,g]])
pt1=clf.predict(t1)
pt1

array([11])