In [ ]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

In [ ]:
data=pd.read_csv('forestfires.csv')
data.columns

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')

In [ ]:
x=data.iloc[:,[8,9,10]].values
y=data.iloc[:,4].values
print(x)
print(y)

[[ 8.2 51.   6.7]
 [18.  33.   0.9]
 [14.6 33.   1.3]
 ...
 [21.2 70.   6.7]
 [25.6 42.   4. ]
 [11.8 31.   4.5]]
[86.2 90.6 90.6 91.7 89.3 92.3 92.3 91.5 91.  92.5 92.5 92.8 63.5 90.9
 92.9 93.3 91.7 84.9 89.2 86.3 91.  91.8 94.3 90.2 93.5 91.4 92.4 90.9
 93.4 93.5 94.3 88.6 88.6 91.7 91.8 90.3 90.6 90.  90.6 88.1 79.5 90.2
 94.8 92.5 90.1 94.3 90.9 94.2 87.2 87.6 92.9 90.2 92.1 92.1 91.7 92.9
 90.3 92.6 84.  86.6 89.3 89.3 93.  90.2 91.1 91.7 92.4 92.4 92.4 91.7
 91.2 94.3 91.7 88.8 93.3 84.2 86.6 87.6 90.1 91.  91.4 90.2 94.8 92.1
 91.7 92.9 92.9 92.9 93.5 91.7 90.2 91.7 92.3 91.4 91.1 89.7 83.9 69.
 91.4 91.4 91.4 88.8 94.8 92.5 82.1 85.9 91.4 90.2 92.5 88.6 85.9 91.7
 89.7 91.8 88.1 88.1 91.7 91.7 90.1 93.  91.5 91.5 92.4 84.4 94.3 92.6
 87.6 93.5 91.4 92.6 68.2 87.2 89.3 93.7 88.1 93.5 92.4 90.9 85.8 91.
 90.9 95.5 90.1 90.  95.5 95.2 90.1 84.4 94.8 93.7 92.5 90.1 90.1 94.3
 93.4 94.8 93.4 92.1 92.1 92.4 90.1 95.2 90.6 92.5 89.7 84.9 92.1 96.
 91.2 95.2 92.9 85.6 91.4 90.9 90.2 9

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.5,random_state=3)
# for checking the values
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 21.8  34.    2.2]
 [ 23.1  31.    3.1]
 [ 12.2  66.    4.9]
 [ 17.4  56.    5.4]
 [ 22.3  46.    4. ]
 [ 18.7  53.    1.8]
 [ 22.1  34.    1.8]
 [ 24.2  28.    3.6]
 [ 24.1  27.    3.1]
 [ 20.1  58.    4.5]
 [ 19.2  24.    4.9]
 [ 23.7  40.    1.8]
 [ 22.5  42.    5.4]
 [ 14.7  66.    2.7]
 [ 26.3  39.    3.1]
 [ 24.8  29.    2.2]
 [ 19.1  39.    5.4]
 [ 17.8  56.    1.8]
 [ 19.8  47.    2.7]
 [ 22.1  54.    7.6]
 [ 21.9  43.    4. ]
 [ 20.4  41.    1.8]
 [  4.6  21.    8.5]
 [ 16.6  53.    5.4]
 [ 25.3  27.    2.7]
 [ 19.7  41.    1.8]
 [ 22.6  38.    3.6]
 [ 18.4  42.    6.7]
 [ 19.2  38.    4.5]
 [ 21.9  71.    5.8]
 [ 18.2  82.    4.5]
 [ 27.8  27.    3.1]
 [ 26.8  38.    6.3]
 [ 24.3  33.    3.6]
 [ 12.8  64.    3.6]
 [ 24.2  27.    3.1]
 [ 19.3  39.    3.6]
 [ 22.8  39.    3.6]
 [ 25.1  27.    4. ]
 [ 26.8  25.    3.1]
 [ 15.2  31.    8.5]
 [ 23.7  25.    4.5]
 [ 25.9  41.    3.6]
 [ 19.9  44.    3.1]
 [ 23.4  22.    2.7]
 [ 25.6  42.    4. ]
 [ 18.6  49.    3.6]
 [ 21.5  15. 

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x)
print(y)

[[ 8.2 51.   6.7]
 [18.  33.   0.9]
 [14.6 33.   1.3]
 ...
 [21.2 70.   6.7]
 [25.6 42.   4. ]
 [11.8 31.   4.5]]
[86.2 90.6 90.6 91.7 89.3 92.3 92.3 91.5 91.  92.5 92.5 92.8 63.5 90.9
 92.9 93.3 91.7 84.9 89.2 86.3 91.  91.8 94.3 90.2 93.5 91.4 92.4 90.9
 93.4 93.5 94.3 88.6 88.6 91.7 91.8 90.3 90.6 90.  90.6 88.1 79.5 90.2
 94.8 92.5 90.1 94.3 90.9 94.2 87.2 87.6 92.9 90.2 92.1 92.1 91.7 92.9
 90.3 92.6 84.  86.6 89.3 89.3 93.  90.2 91.1 91.7 92.4 92.4 92.4 91.7
 91.2 94.3 91.7 88.8 93.3 84.2 86.6 87.6 90.1 91.  91.4 90.2 94.8 92.1
 91.7 92.9 92.9 92.9 93.5 91.7 90.2 91.7 92.3 91.4 91.1 89.7 83.9 69.
 91.4 91.4 91.4 88.8 94.8 92.5 82.1 85.9 91.4 90.2 92.5 88.6 85.9 91.7
 89.7 91.8 88.1 88.1 91.7 91.7 90.1 93.  91.5 91.5 92.4 84.4 94.3 92.6
 87.6 93.5 91.4 92.6 68.2 87.2 89.3 93.7 88.1 93.5 92.4 90.9 85.8 91.
 90.9 95.5 90.1 90.  95.5 95.2 90.1 84.4 94.8 93.7 92.5 90.1 90.1 94.3
 93.4 94.8 93.4 92.1 92.1 92.4 90.1 95.2 90.6 92.5 89.7 84.9 92.1 96.
 91.2 95.2 92.9 85.6 91.4 90.9 90.2 9

In [ ]:
regr_2 = DecisionTreeRegressor(max_depth=5)

In [ ]:
regr_2.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
y_pred=regr_2.predict(x_test)

In [ ]:
print(y_pred)
print(y_test)

[90.48695652 91.73263158 93.92413793 91.73263158 92.06       91.73263158
 93.92413793 90.48695652 91.73263158 91.73263158 91.73263158 91.73263158
 90.48695652 50.4        87.99166667 91.73263158 63.5        91.73263158
 90.48695652 92.06       87.99166667 92.06       93.92413793 91.73263158
 91.375      91.73263158 90.48695652 91.73263158 93.92413793 91.73263158
 90.48695652 90.48695652 90.48695652 63.5        87.99166667 90.48695652
 90.48695652 91.73263158 92.06       90.48695652 90.48695652 87.99166667
 91.375      92.06       91.73263158 91.73263158 93.92413793 91.73263158
 91.73263158 90.48695652 90.48695652 93.92413793 91.73263158 83.86666667
 93.92413793 91.73263158 90.48695652 90.48695652 93.92413793 83.86666667
 91.73263158 91.73263158 93.92413793 92.06       87.99166667 91.73263158
 90.48695652 92.06       92.06       92.06       91.73263158 90.48695652
 91.73263158 91.73263158 91.73263158 18.7        93.92413793 92.06
 87.99166667 93.92413793 90.48695652 90.48695652 91.73263

In [ ]:
t1=sc.transform([[21.5,86,1]])
pt1=regr_2.predict(t1)
pt1

array([18.7])